### PR TITLE
Move to go modules

### PR DESCRIPTION
**Pull request by oltarzewskik**
It looks like in the previous way of installation you have used the most recent commit from git repo.

Now in order to update for instance `github.com/decred/dcrd/dcrec/secp256k1`  in `go.mod` for example in this case just replace `v3.0.0-20200715155919-cdc897dcc204` with hash of commit that you want, then run `make download-deps` and `go.mod` and `vendor/` should update automatically

I am not sure about including `vendor/` in `.gitignore` because some have it and some don't

@wisepythagoras

### CODE REVIEW

**Comment by wisepythagoras** [comment]
👏 First contribution 👏 I think `vendor/` needs to be removed and to be added in `.gitignore`. It seems odd to add it and it's almost impossible to review the branch.

**Comment by oltarzewskik** [comment]
:+1: added

**Comment by wisepythagoras** [comment]
Sorry, I probably should have specified, but you also need to remove the vendor folder:

```
git rm vendor/
```

**Comment by oltarzewskik** [comment]
I think that I already removed it, or I just misunderstand something?

**Comment by wisepythagoras** [comment]
Ah yes. I see it now.

**Comment by oltarzewskik** [comment]
So for now we may keep this PR as open if so then Makefile needs some change namely now Makefile assumes that your $GOPATH is $HOME/go it should be changed to $GOPATH itself I think

**Comment by wisepythagoras** [comment]
Oh yes, are you talking about [this](https://github.com/wisepythagoras/dimoschain/pull/3/files#diff-b67911656ef5d18c4ae36cb6741b7965L1) piece of code? Yes, this can definitely be changed to `$GOPATH`.

**Comment by wisepythagoras** [comment]
Ok, I think we need to merge your branch @oltarzewskik. I don't want to hold onto old practices anymore. Some updates to be made here:

1. Update `github.com/decred/dcrd/dcrec/secp256k1` to the latest version. Currently you have this version: `v3.0.0-20200715155919-cdc897dcc204`.
2. Update `github.com/dgraph-io/badger` to `v3`.

Am I missing anything? Once we merge your work, I want to add [goreleaser](https://goreleaser.com/quick-start/) so we can build for multiple platforms.

**Comment by oltarzewskik** [comment]
Updated :+1:

**Comment by wisepythagoras** [comment]
:fireworks:

**Pull request merged**
